- name: Synchronize emacs config
  synchronize: src=~../../optional_files/.emacs.d/ dest=~/.emacs.d

- name: Emacs - Update and upgrade Homebrew
  shell: brew update && brew upgrade && brew cleanup

- name: Emacs - Install emacss with Homebrew cask
  homebrew_cask: name=emacs

- name: Emacs - Install cash with Homebrew
  homebrew: name=cask

- file:
    path: ~/Workspaces/emacs
    state: directory
    
- name: Emacs - install neotree
  git:
    repo: git@github.com:jaypei/emacs-neotree.git
    dest: ~/Workspaces/emacs/neotree
    force: yes
    version: dev
    
- name: Emacs - install helm
  git:
    repo: https://github.com/emacs-helm/helm.git
    dest: ~/Workspaces/emacs/helm
    force: yes

# needed for helm
- name: Emacs - install async
  git:
    repo: https://github.com/jwiegley/emacs-async.git
    dest: ~/Workspaces/emacs/async
    force: yes

- name: Emacs - make helm
  shell: /usr/bin/make
  args: 
    chdir: ~/Workspaces/emacs/helm
